# Generated by Django 4.1.5 on 2023-02-02 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='cover_image_file',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
